name: Deploy Python Code to Azure VM

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # This is where the actions will run

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo python3 -m pip install -r requirements.txt
        sudo systemctl restart myapp
        

